root: true
env:
  browser: true
  es2017: true
  jquery: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
rules:
  no-console:
    - off
  no-unused-vars:
    - error
    - args: none
      varsIgnorePattern: '^_$'
  react/no-deprecated: # TODO: enable
    - warn
  '@typescript-eslint/no-explicit-any': # TODO: enable
    - warn
  # TODO: apply the following exception only for react (tsx) files
  # https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492
  '@typescript-eslint/ban-types':
    - error
    - extendDefaults: true
      types:
        '{}': false
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
      varsIgnorePattern: '^_$'
