env:
  browser: true
  es2017: true
  jquery: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  no-console:
    - off
  no-unused-vars:
    - error
    - args: none
  react/prop-types: # TODO: enable
    - warn
  react/no-deprecated: # TODO: enable
    - warn
