env:
  browser: true
  es6: true
  jquery: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  no-console:
    - off
  no-unused-vars:
    - error
    - args: none
  react/prop-types:  # TODO: enable
    - warn
  react/no-deprecated:  # TODO: enable
    - warn
