application: icpcsec
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
  expiration: 0s
- url: /demodata
  static_dir: demodata
- url: /api
  static_dir: demodata
  expiration: 0s
- url: /api
  script: livesite.main.app
- url: .*
  static_files: static/index.html
  upload: static/index.html
