# docker-compose YAML definition
version: '2'

services:

  app:
    image: asia.gcr.io/nya3jp/livesite-app
    command: [./run.sh, "--pyargv=--nologtostderr --logtosyslog --gcs_bucket_name=livesite-dev-nya --gcs_bucket_path_prefix=livesite-canary/ --slack_webhook_url=https://hooks.slack.com/services/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"]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  realtime:
    image: asia.gcr.io/nya3jp/livesite-app
    command: [./run-realtime.sh, --nologtostderr, --logtosyslog]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  ratings:
    image: asia.gcr.io/nya3jp/livesite-app
    command: [./run-ratings.sh, --nologtostderr, --logtosyslog]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  nginx:
    image: asia.gcr.io/nya3jp/livesite-nginx
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /var/cache/munin/www:/mnt
    logging:
      driver: syslog

  mongodb:
    image: mongo:3.2.6
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /opt/livesite/db:/data/db
    logging:
      driver: syslog

  dump:
    image: mongo:3.2.6
    command: [bash, -c, "while :; do mongodump --out /mnt/dump/$$(date +%Y%m%d-%H%M%S); sleep 1h; done"]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /opt/livesite:/mnt
    logging:
      driver: syslog
