# docker-compose YAML definition
version: '2'

services:

  app:
    image: asia.gcr.io/icpcsec/livesite-app:demo
    command: [./run.sh, "--pyargv=--nologtostderr --logtosyslog --gcs_bucket_name=livesite-dev-nya --gcs_bucket_path_prefix=livesite-demo/"]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  realtime:
    image: asia.gcr.io/icpcsec/livesite-app:demo
    command: [./run-realtime.sh, --nologtostderr, --logtosyslog]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  ratings:
    image: asia.gcr.io/icpcsec/livesite-app:demo
    command: [./run-ratings.sh, --nologtostderr, --logtosyslog]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  nginx:
    image: asia.gcr.io/icpcsec/livesite-nginx:demo
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
    logging:
      driver: syslog

  mongodb:
    image: mongo:3.2.6
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /opt/livesite/db:/data/db
    logging:
      driver: syslog

  dump:
    image: mongo:3.2.6
    command: [bash, -c, "while :; do mongodump --out /mnt/dump/$$(date +%Y%m%d-%H%M%S); sleep 1h; done"]
    restart: always
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /opt/livesite:/mnt
    logging:
      driver: syslog
