# This is a docker-compose configuration used for the production server.
version: '2'

networks:
  default:
    driver: bridge

services:
  app:
    image: asia.gcr.io/icpcsec/livesite-app:latest
    command:
      - "bin/run-prod.sh"
    restart: always
    depends_on:
      - mongodb

  realtime:
    image: asia.gcr.io/icpcsec/livesite-app:latest
    command:
      - "bin/run-realtime.sh"
    restart: always
    depends_on:
      - mongodb

  nginx:
    image: asia.gcr.io/icpcsec/livesite-nginx:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
      - realtime

  mongodb:
    image: mongo:3.2.6
    restart: always
    volumes:
      - /opt/livesite/db:/data/db

  # Periodically backup the database.
  dump:
    image: mongo:3.2.6
    command:
      - "bash"
      - "-c"
      - "mkdir -p /mnt/dump; while :; do mongodump --host mongodb --out /mnt/dump/$$(date +%Y%m%d-%H%M%S); sleep 1h; done"
    volumes:
      - /opt/livesite/db:/mnt
    restart: always
    depends_on:
      - mongodb
