FROM python:2

RUN apt-get update && apt-get install -y graphviz nodejs && apt-get clean && ln -s nodejs /usr/bin/node

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

WORKDIR /opt/livesite/app/build/dev

ENV PYTHONPATH=/opt/livesite/app/build/dev
ENTRYPOINT ["/opt/livesite/app/build/dev/bin/dumb-init", "--"]

CMD bin/run-dev.sh
